
file=open('file.txt','r')
print(file.read())
file.close()
file_write=open('file.txt','w')
file_write.write("Hii i am Raza i love to do coding")
file_write.close()
file_append=open("file.txt",'a')
file_append.write("Hello i am Heet")
file_append.close()